version: '3'

services:
  glb-intelligence-ui:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: glb-intelligence-ui
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
